# Generated by Django 3.2.9 on 2022-02-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_product_category'),
        ('mainapp', '0003_product_is_active'),
    ]

    operations = [
    ]
